### ISSUE TITLE
Bose SoundLink Air WiFi latest firmware

### ISSUE THREAD

**Issue by fr3man2** [bosefirmware/ced-old#2]
Are you able to provide latest firmware version binary ? 
Only initial update.fw 112.9187 is available.
I am looking for a version 1.2.5 mentioned in
https://www.bose.ca/en_ca/support/articles/HC2300/productCodes/soundlink_air/article.html

**Comment by fr3man2** [comment]
also http://worldwide.bose.com/soundlinkair seems to be dead

**Comment by orionnelson** [comment]
+1
